USE shoeshopjpa;

INSERT INTO INVENTORY (CAPACITY) VALUES (500);
INSERT INTO INVENTORY (CAPACITY) VALUES (300);
INSERT INTO INVENTORY (CAPACITY) VALUES (1000);

INSERT INTO ADDRESS (LOCATION) VALUES ('Carrer de la Marina, 1, Barcelona');
INSERT INTO ADDRESS (LOCATION) VALUES ('Avinguda Diagonal, 200, Barcelona');
INSERT INTO ADDRESS (LOCATION) VALUES ('Passeig de Gràcia, 50, Barcelona');

INSERT INTO MODEL (NAME, BRAND) VALUES ('Air Max', 'Nike');
INSERT INTO MODEL (NAME, BRAND) VALUES ('Superstar', 'Adidas');
INSERT INTO MODEL (NAME, BRAND) VALUES ('Classic', 'Reebok');

INSERT INTO SHOE_STORE (NAME, OWNER, LOCATION) VALUES ('Foot MDN - Carrer de la Marina', 'Martí Corder', 'Carrer de la Marina, 1, Barcelona');
INSERT INTO SHOE_STORE (NAME, OWNER, LOCATION) VALUES ('Foot MDN - Avinguda Diagonal', 'Martí Corder', 'Avinguda Diagonal, 200, Barcelona');
INSERT INTO SHOE_STORE (NAME, OWNER, LOCATION) VALUES ('Foot MDN - Passeig de Gràcia', 'Martí Corder', 'Passeig de Gràcia, 50, Barcelona');

INSERT INTO SUPPLIER (NAME, PHONE) VALUES ('Global Shoes', '123456789');
INSERT INTO SUPPLIER (NAME, PHONE) VALUES ('Top Footwear', '987654321');
INSERT INTO SUPPLIER (NAME, PHONE) VALUES ('Best Shoes Supply', '555444333');

INSERT INTO CLIENT (DNI, NAME, PHONE, ADDRESS_ID, SHOE_STORE_ID) VALUES ('12345678A', 'Alice Brown', '666555444', 1, 1);
INSERT INTO CLIENT (DNI, NAME, PHONE, ADDRESS_ID, SHOE_STORE_ID) VALUES ('87654321B', 'Bob White', '444555666', 2, 2);
INSERT INTO CLIENT (DNI, NAME, PHONE, ADDRESS_ID, SHOE_STORE_ID) VALUES ('11223344C', 'Charlie Black', '333222111', 3, 3);

INSERT INTO SHOE (MODEL_ID, INVENTORY_ID, PRICE, COLOR, SIZE) VALUES (1, 1, 120.00, 'Red', '42');
INSERT INTO SHOE (MODEL_ID, INVENTORY_ID, PRICE, COLOR, SIZE) VALUES (2, 2, 90.00, 'White', '40');
INSERT INTO SHOE (MODEL_ID, INVENTORY_ID, PRICE, COLOR, SIZE) VALUES (3, 3, 110.00, 'Black', '44');

INSERT INTO SHOE_STORE_INVENTORY (SHOE_STORE_ID, INVENTORY_ID) VALUES (1, 1);
INSERT INTO SHOE_STORE_INVENTORY (SHOE_STORE_ID, INVENTORY_ID) VALUES (2, 2);
INSERT INTO SHOE_STORE_INVENTORY (SHOE_STORE_ID, INVENTORY_ID) VALUES (3, 3);

INSERT INTO SHOE_STORE_SUPPLIER (SHOE_STORE_ID, SUPPLIER_ID) VALUES (1, 1);
INSERT INTO SHOE_STORE_SUPPLIER (SHOE_STORE_ID, SUPPLIER_ID) VALUES (2, 2);
INSERT INTO SHOE_STORE_SUPPLIER (SHOE_STORE_ID, SUPPLIER_ID) VALUES (3, 3);