/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(project(":domain-implementations:jdbc"))
    implementation(project(":domain-implementations:JPA"))
    implementation("com.mysql:mysql-connector-j:8.3.0")
    implementation(project(":domain-implementations:file"))
    implementation("com.github.freva:ascii-table:1.8.0")

}

application {
    mainClass = "org.example.app.App"
}
