CREATE DATABASE Shoe_Shop;

USE	 Shoe_Shop;

CREATE TABLE INVENTORY (
    ID_INVENTORY INT PRIMARY KEY,
    CAPACITY INT
);

CREATE TABLE ADRESS (
    ID_ADRESS INT PRIMARY KEY
);

CREATE TABLE MODEL (
    ID_MODEL INT PRIMARY KEY,
    NAME VARCHAR(255),
    BRAND VARCHAR(255)
);

CREATE TABLE SHOE_STORE (
    ID_STORE INT PRIMARY KEY,
    NAME VARCHAR(255),
    OWNER VARCHAR(255),
    LOCATION VARCHAR(255),
    ID_INVENTORY INT,
    FOREIGN KEY (ID_INVENTORY) REFERENCES INVENTORY(ID_INVENTORY)
);

CREATE TABLE SUPPLIER (
    ID_SUPPLIER INT PRIMARY KEY,
    NAME VARCHAR(255),
    PHONE VARCHAR(15)
);

CREATE TABLE CLIENT (
    DNI VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(255),
    PHONE VARCHAR(15),
    ID_ADDRESS INT,
    FOREIGN KEY (ID_ADRESS) REFERENCES ADRESS(ID_ADRESS)
);

CREATE TABLE SHOE (
    ID_SHOE INT PRIMARY KEY,
    ID_MODEL INT,
    ID_INVENTORY INT,
    PRICE DECIMAL(10, 2),
    COLOR VARCHAR(50),
    SIZE VARCHAR(10),
    FOREIGN KEY (ID_MODEL) REFERENCES MODEL(ID_MODEL),
    FOREIGN KEY (ID_INVENTORY) REFERENCES INVENTORY(ID_INVENTORY)
);

CREATE TABLE LINK_STORE_SUPPLIER (
    ID_STORE INT,
    ID_SUPPLIER INT,
    PRIMARY KEY (ID_STORE, ID_SUPPLIER),
    FOREIGN KEY (ID_STORE) REFERENCES SHOE_STORE(ID_STORE),
    FOREIGN KEY (ID_SUPPLIER) REFERENCES SUPPLIER(ID_SUPPLIER)
);

CREATE TABLE LINK_CLIENT_STORE (
    DNI VARCHAR(20),
    ID_STORE INT,
    PRIMARY KEY (DNI, ID_STORE),
    FOREIGN KEY (DNI) REFERENCES CLIENT(DNI),
    FOREIGN KEY (ID_STORE) REFERENCES SHOE_STORE(ID_STORE)
);

