GET http://localhost:8080/address
Accept: application/json
###
GET http://localhost:8080/address/9
Accept: application/json
###
DELETE http://localhost:8080/address/9
Accept: application/json
###
PUT http://localhost:8080/address/2
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "location": "Carrer Novembre"
}
###
POST http://localhost:8080/address
Accept: application/json
Content-Type: application/json

{
  "location": "Carrer Sant Antoni"
}
