GET http://localhost:8080/client
Accept: application/json
###
GET http://localhost:8080/client/1
Accept: application/json
###
DELETE http://localhost:8080/client/1
Accept: application/json
###
PUT http://localhost:8080/client/2
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "dni": "12345678A",
  "name": "Client A (Updated)",
  "phone": "111222333",
  "addresses": {
    "id": 2,
    "location": "Street A (Updated)"
  },
  "shoeStores": {
    "id": 1,
    "name": "Shoe Store A (Updated)"
  }
}


###
POST http://localhost:8080/client
Accept: application/json
Content-Type: application/json

{
  "dni": "11223344C",
  "name": "Client C",
  "phone": "333444555",
  "addresses": {
    "location": "Street C"
  },
  "shoeStores": {
    "id": 3,
    "name": "Shoe Store C"
  }
}

###