GET http://localhost:8080/clients
Accept: application/json
###
GET http://localhost:8080/clients/6
Accept: application/json
###
DELETE http://localhost:8080/clients/8
Accept: application/json
###
PUT http://localhost:8080/clients/4
Accept: application/json
Content-Type: application/json

{
  "dni": "48955663F",
  "name": "ORIOL",
  "phone": "686771035",
  "addresses": {
    "id": 2,
    "location": "Carrer Romeu"
  },
  "shoeStores": {
    "id": 1,
    "name": "FutbolManager"
  }
}
###
POST http://localhost:8080/clients
Accept: application/json
Content-Type: application/json

{
  "dni": "46781345C",
  "name": "Roger",
  "phone": "670051644",
  "addresses": {
    "location": "Carretera Viladrau"
  },
  "shoeStores": {
    "id": 3,
    "name": "FutbolManager Pro"
  }
}
