GET http://localhost:8080/inventories
Accept: application/json
###
GET http://localhost:8080/inventories/15
Accept: application/json
###
DELETE http://localhost:8080/inventories/14
Accept: application/json
###
PUT http://localhost:8080/inventories/5
Accept: application/json
Content-Type: application/json

{
  "capacity": 150,
  "shoeStores": null,
  "shoes": null
}
###
POST http://localhost:8080/inventories
Accept: application/json
Content-Type: application/json

{
  "capacity": 200,
  "shoeStores": [
    {
      "id": 1,
      "name": "FutbolManager A",
      "location": "Taradell"
    }
  ],
  "shoes": [
    {
      "id": 1,
      "price": 75.00,
      "color": "Blue",
      "size": "43"
    }
  ]
}
