### GET request to example server
# curl -X GET http://localhost:8080/clients
GET http://localhost:8080/clients

###
# curl -X POST http://localhost:8080/clients

POST http://localhost:8080/clients
Content-Type: application/json

{
  "dni": "12345678X",
  "name": "Roger Gost"
}

###
