GET http://localhost:8080/shoeStores
Accept: application/json
###
GET http://localhost:8080/shoeStores/2
Accept: application/json
###
DELETE http://localhost:8080/shoeStores/3
Accept: application/json
###
PUT http://localhost:8080/shoeStores/2
Accept: application/json
Content-Type: application/json

{
  "name": "FutbolManager B",
  "owner": "Martí C",
  "location": "Vic",
  "suppliers": [
    {
      "id": 1,
      "name": "Undirect"
    }
  ],
  "clients": [
    {
      "id": 3,
      "name": "Roger Valverde"
    }
  ],
  "inventories": [
    {
      "id": 5,
      "capacity": 300
    }
  ]
}
###
POST http://localhost:8080/shoeStores
Accept: application/json
Content-Type: application/json

{
  "name": "FutbolManager Direction",
  "owner": "Martí C",
  "location": "Madrid",
  "suppliers": [
    {
      "id": 1
    }
  ],
  "clients": [
    {
      "id": 2
    }
  ],
  "inventories": [
    {
      "id": 2
    }
  ]
}
