GET http://localhost:8080/shoe
Accept: application/json
###
GET http://localhost:8080/shoe/1
Accept: application/json
###
DELETE http://localhost:8080/shoe/4
Accept: application/json
###
PUT http://localhost:8080/shoe/4
Accept: application/json
Content-Type: application/json

{
  "price": 120,
  "color": "Blue",
  "size": "44",
  "models": {
    "id": 1
  },
  "inventories": {
    "id": 1
  }
}
###
POST http://localhost:8080/shoe
Accept: application/json
Content-Type: application/json

{
  "price": 120,
  "color": "Red",
  "size": "44",
  "models": {
    "id": 1
  },
  "inventories": {
    "id": 1
  }
}

