GET http://localhost:8080/supplier
Accept: application/json
###
GET http://localhost:8080/supplier/1
Accept: application/json
###
DELETE http://localhost:8080/supplier/1
Accept: application/json
###
PUT http://localhost:8080/supplier/2
Accept: application/json
Content-Type: application/json

{
  "NAME": "ShoeDirect",
  "PHONE": "931877658",
  "SHOE_STORE_ID": 2
}
###
POST http://localhost:8080/supplier
Accept: application/json
Content-Type: application/json

{
  "NAME": "SuppliShoe",
  "PHONE": "983776831",
  "SHOE_STORE_ID": 3
}
