GET http://localhost:8080/supplier
Accept: application/json
###
GET http://localhost:8080/supplier/4
Accept: application/json
###
DELETE http://localhost:8080/supplier/5
Accept: application/json
###
PUT http://localhost:8080/supplier/6
Accept: application/json
Content-Type: application/json

{
  "name": "ShoeDirect",
  "phone": "931877658",
  "shoeStores": [
  {
    "id": 1
  },
  {
    "id": 2
  }
]
}
###
POST http://localhost:8080/supplier
Accept: application/json
Content-Type: application/json

{
  "name": "SuppliShoe",
  "phone": "983776831",
  "shoeStores": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}
